name: Generate Snake

on:
  schedule:
    - cron: "0 0 */2 * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: Platane/snk@v3
        with:
          github_user_name: hkxdv
          outputs: |
            dist/snake-purple-dark.svg?color_snake=#FF007A&color_dots=#161b22,#2A0A4F,#5A1D7E,#9745F5,#E040FB
            dist/snake-purple-light.svg?color_snake=#FF007A&color_dots=#EBEDF0,#FCDDED,#F8B0D9,#E040FB,#9745F5
            dist/snake-monochrome-accent-dark.svg?color_snake=#D1D5DA&color_dots=#161b22,#30363D,#484F58,#6E7681,#9745F5
            dist/snake-monochrome-accent-light.svg?color_snake=#24292E&color_dots=#EBEDF0,#F6F8FA,#D1D5DA,#AEB5BC,#9745F5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and push if changed
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add dist
          if ! git diff --staged --quiet; then
            git commit -m "[ci] update snk animation"
            git pull --rebase
            git push
          else
            echo "No changes to commit."
          fi
